version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "metrics"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../../db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      - "9090:8080"
    networks:
      - metrics_go

volumes:
  postgres_data:

networks:
  metrics_go:
    external: true

